from pathlib import Path
from bs4 import BeautifulSoup

FILES = sorted(Path('.').glob('kj-somaiya-institute-of-management*.html'))

CUTOFF = '''
<div class="source-note"><strong>Important:</strong> KJSIM's current official admission page says merit-based candidates are shortlisted using institute cutoffs, but the page reviewed does not publish one fixed numeric cutoff. The figures below are <strong>student/community and third-party reference points</strong>, not official KJSIM cutoffs.</div>
<div class="data-grid">
<div class="data-card"><span class="data-label">CAT 2026 reference</span><strong>82–87 percentile</strong><p>PaGaLGuY's 2026 expected range. Use it only as an application-planning benchmark.</p></div>
<div class="data-card"><span class="data-label">XAT 2026 reference</span><strong>70–85 percentile</strong><p>PaGaLGuY's 2026 expected range. A 2026 Reddit conversion experience also reports 87.5 XAT.</p></div>
<div class="data-card"><span class="data-label">CMAT 2026 reference</span><strong>94–98 percentile</strong><p>PaGaLGuY's 2026 expected range; a March 2026 Reddit discussion mentioned about 98.xx as a student-reported reference.</p></div>
<div class="data-card"><span class="data-label">NMAT 2026 reference</span><strong>223–230</strong><p>PaGaLGuY's 2026 expected score range. This is not an official KJSIM threshold.</p></div>
</div>
<h3>What student discussions add to the picture</h3>
<div class="discussion-box"><p><strong>Reddit, April 2026:</strong> a candidate reported converting KJSIM with 87.5 XAT after scoring 77 CAT, and described the interview and ROI considerations. This is an individual outcome, not a rule.</p><p><strong>Reddit, March 2026:</strong> a KJSIM/NMAT-CMAT discussion included a user-reported CMAT reference of about 98.xx for shortlisting.</p><p><strong>PaGaLGuY, 2026:</strong> the KJSIM college page currently publishes expected 2026 ranges across CAT, XAT, CMAT and NMAT.</p></div>
<div class="discussion-links"><a href="https://www.reddit.com/r/CATpreparation/comments/1smpoz7/875_ile_in_xat_3_years_gap_terrible_interview/" target="_blank" rel="noopener">Reddit: 87.5 XAT KJSIM conversion experience ↗</a><a href="https://www.reddit.com/r/NMATpreparation/comments/1rox2td/kj_somaiya/" target="_blank" rel="noopener">Reddit: KJSIM CMAT shortlisting discussion ↗</a><a href="https://www.pagalguy.com/colleges/kj-somaiya-institute-of-management-studies-and-research-simsr-mumbai" target="_blank" rel="noopener">PaGaLGuY: KJSIM cutoff reference page ↗</a></div>
<div class="warning-box"><h3>So, what should you target?</h3><p>Do not treat a single percentile as a guaranteed call. KJSIM also considers academics, work experience and profile-based shortlisting, followed by PSA/WAT/PI evaluation. A score inside a community range can still produce different outcomes for different profiles.</p></div>
'''

PLACEMENT = '''
<div class="answer-box placement-answer"><strong>Latest official MBA placement outcome</strong><p>For MBA 2024–26, KJSIM reports a <strong>₹29.30 LPA highest package</strong>, <strong>₹12 LPA median CTC</strong> and <strong>210 recruiters</strong>. For the 2025–27 internship cycle, the institute reports <strong>126 recruiters</strong> and a <strong>₹3 lakh highest stipend</strong>.</p></div>
<div class="data-grid"><div class="data-card"><span class="data-label">Highest CTC</span><strong>₹29.30 LPA</strong><p>Top-end outcome; it should not be read as the typical salary.</p></div><div class="data-card"><span class="data-label">Median CTC</span><strong>₹12 LPA</strong><p>More useful than the highest package for understanding the middle of the reported outcomes.</p></div><div class="data-card"><span class="data-label">Final recruiters</span><strong>210</strong><p>Reported MBA 2024–26 recruiter participation.</p></div><div class="data-card"><span class="data-label">Internship recruiters</span><strong>126</strong><p>Reported for the 2025–27 internship cycle.</p></div></div>
<h3>Placement metrics students should compare</h3>
<div class="table-wrapper"><table><tr><th>Metric</th><th>Latest figure</th><th>What it tells you</th></tr><tr><td>Highest CTC</td><td>₹29.30 LPA</td><td>Upper-end outcome, not the batch norm.</td></tr><tr><td>Median CTC</td><td>₹12 LPA</td><td>Better indicator of the middle of the reported salary distribution.</td></tr><tr><td>Recruiters</td><td>210</td><td>Employer participation breadth; not the number of offers per recruiter.</td></tr><tr><td>Internship recruiters</td><td>126</td><td>Scale of summer internship participation.</td></tr><tr><td>Highest stipend</td><td>₹3 lakh</td><td>Top internship outcome, not average stipend.</td></tr><tr><td>Top 10% internship average</td><td>₹1,43,950</td><td>Upper-segment internship benchmark.</td></tr><tr><td>Top 20% internship average</td><td>₹1,14,394</td><td>Another upper-segment internship benchmark.</td></tr></table></div>
<h3>How KJSIM builds placement readiness</h3><p>The institute's Professional Development &amp; Placement model includes guest lectures, competitions, corporate projects, full-time summer internships and final placements. Students therefore get employer interaction and applied exposure before the final recruitment season.</p><div class="placement-path"><div><strong>Industry interaction</strong><span>Guest lectures, competitions and corporate engagement.</span></div><div><strong>Applied exposure</strong><span>Corporate projects and summer internships.</span></div><div><strong>Final recruitment</strong><span>Permanent employment opportunities through participating recruiters.</span></div><div><strong>Student evaluation</strong><span>Compare role, fixed pay, location and growth—not only the recruiter logo.</span></div></div>
<h3>Recruiters and roles: how to evaluate them</h3><p>Recent third-party reporting lists employers such as <strong>Mercedes-Benz, Cisco, J.P. Morgan, Salesforce, Wipro, Maruti Suzuki, Piramal Pharma and General Mills</strong>. Employer participation can change by batch, function and hiring demand, so these should be treated as recent examples rather than a guaranteed list.</p><p>For ROI decisions, ask four questions: <strong>What role was offered? What was the fixed component? How many students were hired? What is the location and career path?</strong> A high-profile recruiter name alone does not prove a stronger placement outcome.</p>
<div class="discussion-links"><a href="https://kjsim.somaiya.edu/en/professional-development-placement/" target="_blank" rel="noopener">KJSIM official placement page ↗</a><a href="https://www.careers360.com/colleges/k-j-somaiya-institute-of-management-mumbai/placement" target="_blank" rel="noopener">Careers360 placement reporting ↗</a><a href="https://collegedunia.com/college/18230-kj-somaiya-institute-of-management-mumbai/placement" target="_blank" rel="noopener">CollegeDunia placement reporting ↗</a></div>
'''

DECISION = '''<p>KJSIM can make sense for students who value Mumbai's corporate ecosystem, broad management exposure and programme flexibility, but the decision should be made using the <strong>median salary, total cost, role quality and personal financing</strong> rather than the highest package alone.</p><div class="decision-grid"><div class="decision-card"><strong>Good fit</strong><span>Broad MBA, major/minor flexibility and strong Mumbai industry exposure.</span></div><div class="decision-card"><strong>Check ROI</strong><span>Compare the ₹12 LPA median CTC with the programme fee plus hostel/living costs and loan interest.</span></div><div class="decision-card"><strong>Check your profile</strong><span>Cutoff is only one part of the process; academics, work experience and PSA/WAT/PI matter.</span></div><div class="decision-card"><strong>Check the job, not just CTC</strong><span>Function, fixed pay, location and growth potential can change the value of an offer.</span></div></div>'''

FAQ = '''<div class="faq-item"><h3>What is the official KJ Somaiya CAT cutoff?</h3><p>The current official page confirms that KJSIM uses institute cutoffs for merit-based shortlisting but does not publish one fixed numeric CAT cutoff on the page reviewed.</p></div><div class="faq-item"><h3>What CAT percentile is discussed by students?</h3><p>Current community references commonly place CAT expectations in the low-to-high 80s. These are planning references, not guaranteed shortlisting thresholds.</p></div><div class="faq-item"><h3>Is ₹29.30 LPA the average package?</h3><p>No. ₹29.30 LPA is the reported highest CTC. The latest official placement page reports ₹12 LPA median CTC.</p></div>'''

CSS = '''.data-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0}.data-card,.decision-card{border:1px solid #d8e0ea;border-radius:12px;padding:18px;background:#fff;box-shadow:0 3px 12px rgba(20,40,70,.05)}.data-card .data-label{display:block;font-size:.78rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:#536b83;margin-bottom:7px}.data-card strong{display:block;font-size:1.28rem;color:#123b67;margin-bottom:7px}.data-card p{margin:0;line-height:1.55}.source-note{margin:18px 0;padding:14px 16px;border-left:4px solid #2b6fd6;background:#f4f8fd;border-radius:8px;line-height:1.6}.discussion-box{margin:16px 0;padding:18px;background:#fafbfd;border:1px solid #dce4ee;border-radius:10px}.discussion-box p{margin:0 0 12px}.discussion-box p:last-child{margin-bottom:0}.discussion-links{display:flex;flex-wrap:wrap;gap:9px;margin:16px 0}.discussion-links a{display:inline-block;padding:9px 12px;border:1px solid #c9d7e8;border-radius:7px;background:#fff;color:#135dcc;text-decoration:none;font-weight:600;font-size:.9rem}.placement-path{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:18px 0}.placement-path>div{padding:15px;border-radius:10px;background:#f6f8fb;border:1px solid #dce3ec}.placement-path strong,.placement-path span{display:block}.placement-path strong{margin-bottom:6px;color:#123b67}.placement-path span{font-size:.92rem;line-height:1.45}.decision-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}.decision-card strong,.decision-card span{display:block}.decision-card strong{margin-bottom:7px;color:#123b67}.decision-card span{line-height:1.55}.main-section h3{margin-top:24px}.table-wrapper table td,.table-wrapper table th{vertical-align:top}@media(max-width:800px){.data-grid,.decision-grid{grid-template-columns:1fr}.placement-path{grid-template-columns:1fr 1fr}.discussion-links{display:grid;grid-template-columns:1fr}.discussion-links a{text-align:center}}@media(max-width:520px){.placement-path{grid-template-columns:1fr}.data-card,.decision-card{padding:15px}}'''

def replace_section(soup, sid, title, body):
    sec = soup.find('section', id=sid)
    if not sec:
        return
    sec.clear()
    h = soup.new_tag('h2')
    h.string = title
    sec.append(h)
    frag = BeautifulSoup(body, 'html.parser')
    for node in list(frag.contents):
        sec.append(node)

for path in FILES:
    soup = BeautifulSoup(path.read_text(encoding='utf-8'), 'html.parser')
    if not soup.find('link', href='kjsim-enhancements.css'):
        link = soup.new_tag('link', rel='stylesheet', href='kjsim-enhancements.css')
        soup.head.append(link)
    replace_section(soup, 'cutoff', 'KJ Somaiya MBA Cutoff: Official Position + Student Reference Range', CUTOFF)
    replace_section(soup, 'placements', 'KJ Somaiya Placements: Latest MBA Outcomes, Roles & ROI', PLACEMENT)
    replace_section(soup, 'decision', 'Is KJ Somaiya a Good Fit for You?', DECISION)
    faq = soup.find('section', id='faqs')
    if faq and not faq.find(string=lambda x: x and 'What is the official KJ Somaiya CAT cutoff?' in x):
        frag = BeautifulSoup(FAQ, 'html.parser')
        for node in list(frag.contents):
            faq.append(node)
    if path.name.endswith('-placements.html'):
        replace_section(soup, 'latest', 'KJ Somaiya Placements: Latest Official Highlights', PLACEMENT)
        replace_section(soup, 'snapshot', 'Placement Snapshot: What the Numbers Actually Mean', '''<div class="data-grid"><div class="data-card"><span class="data-label">Highest CTC</span><strong>₹29.30 LPA</strong><p>MBA 2024–26 top-end outcome.</p></div><div class="data-card"><span class="data-label">Median CTC</span><strong>₹12 LPA</strong><p>MBA 2024–26 middle-of-distribution benchmark.</p></div><div class="data-card"><span class="data-label">Final recruiters</span><strong>210</strong><p>MBA 2024–26 reported recruiter participation.</p></div><div class="data-card"><span class="data-label">Internship recruiters</span><strong>126</strong><p>2025–27 internship cycle.</p></div></div><p>Use median rather than highest CTC when estimating what a typical student may experience. Use recruiter count as an indicator of employer breadth, not as a proxy for placement quality.</p>''')
        replace_section(soup, 'recruiters', 'KJ Somaiya Recruiters, Roles & Industry Exposure', '''<p>KJSIM's placement ecosystem includes guest lectures, corporate competitions, corporate projects, summer internships and final placements. Recent third-party reporting has listed employers such as Mercedes-Benz, Cisco, J.P. Morgan, Salesforce, Wipro, Maruti Suzuki, Piramal Pharma and General Mills.</p><p>Recruiter participation varies by batch and hiring requirement. Students should therefore evaluate the <strong>role, function, fixed pay, location and number of offers</strong> rather than relying on the recruiter logo alone.</p><div class="source-note">Recruiter examples are from recent third-party reporting; the official KJSIM page is the primary source for the latest headline placement metrics.</div>''')
        replace_section(soup, 'internships', 'KJ Somaiya Summer Internships: Stipend & Exposure', '''<div class="data-grid"><div class="data-card"><span class="data-label">Recruiters</span><strong>126</strong><p>Reported for the 2025–27 internship cycle.</p></div><div class="data-card"><span class="data-label">Highest stipend</span><strong>₹3 lakh</strong><p>Top reported internship stipend.</p></div><div class="data-card"><span class="data-label">Top 10% average</span><strong>₹1,43,950</strong><p>Upper-segment internship benchmark.</p></div><div class="data-card"><span class="data-label">Top 20% average</span><strong>₹1,14,394</strong><p>Upper-segment internship benchmark.</p></div></div><p>The institute describes summer internships as full-time practical exposure and also highlights corporate projects as part of its professional-development model.</p>''')
        replace_section(soup, 'yearwise', 'KJ Somaiya Placement Trends: How to Compare Batches', '''<p>Compare batches only when the <strong>programme, batch, metric and reporting definition</strong> are the same. Mixing different sources can create a misleading trend.</p><div class="warning-box"><h3>Why the page avoids an artificial year-wise salary chart</h3><p>The current official placement highlights give the strongest comparable figures for the latest batch. Where an older report uses a different scope or metric, it should not be merged into a single trend line without qualification.</p></div>''')
        replace_section(soup, 'interpretation', 'How Students Should Interpret KJ Somaiya Placements', DECISION + '<div class="discussion-links"><a href="https://kjsim.somaiya.edu/en/professional-development-placement/" target="_blank" rel="noopener">Official KJSIM placement page ↗</a><a href="https://www.careers360.com/colleges/k-j-somaiya-institute-of-management-mumbai/placement" target="_blank" rel="noopener">Careers360 placement reporting ↗</a><a href="https://collegedunia.com/college/18230-kj-somaiya-institute-of-management-mumbai/placement" target="_blank" rel="noopener">CollegeDunia placement reporting ↗</a></div>')
    path.write_text(str(soup), encoding='utf-8')

Path('kjsim-enhancements.css').write_text(CSS, encoding='utf-8')
print('Enhanced', len(FILES), 'KJSIM pages')
